arturo-lang/arturo

- .github/workflows/release.yml
CI builds arturo and uploads arturo to GitHub Releases when 'git tag' was pushed.
Users don't have to run 'build.sh' or 'nimble build'.
```bash
$ git tag v0.9.5
$ git push origin --tags
```
> add workflow to release to GitHub Release

- .github/workflows/linux.yml
- .github/workflows/windows.yml
`set-env` is deprecated commands.
see: [GitHub Actions: Deprecating set-env and add-path commands](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
Using [Setting an environment variable](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable).
> fix: deprecated code (set-env)

- src/library/Converters.nim
This would make `to :char 20320` return `你` instead of junk char.
> Support conversion from integer to any char

- .gitattributes
Render files on GitHub using the same Red linguist grammar as used in Markdown files
> Add .gitattributes for GitHub file highlighting

- src/library/Iterators.nim
I added some `gather` examples to documentation.
It's not complete. It's missing `with` option (I couldn't use, or didn't know how to use it) 
Tries to fix #759
> Add `gather` documentation

- src/helpers/arrays.nim
- src/vm/values/clean.nim
This PR adds internal documentation to some functions.
I think it must to need a review.
1. I closed the [last PR](https://github.com/arturo-lang/arturo/pull/764) because I committed a error. I explained why [here](https://github.com/arturo-lang/arturo/pull/764#issuecomment-1280022997)
2. I think we'll need a new label, to don't conflict user and developer documentation issues/pr labels
- The label can be `dev-documentation`, `dev-doc`, `internal-documentation`, `internal-doc`, what you want 🙂
> Add internal documentation

- src/vm/values/custom/vbinary.nim
Stops using `sequtils` for binary ops which will reduce memory allocations a bit. Resulting in faster code when used.
> [VBinary] Made loop ops more memory efficient

- src/library/Core.nim
Adds missing example of how to properly use FFI in Arturo.
>Note: It'll cover both `.expect` and `.external` 
The current documentation does not cover this feature, and I had to search into Rosetta examples to discover how to use it:
[call a foreign-language function.c](https://github.com/arturo-lang/arturo/blob/master/examples/rosetta/call%20a%20foreign-language%20function.c)
[call a foreign-language function.art](https://github.com/arturo-lang/arturo/blob/master/examples/rosetta/call%20a%20foreign-language%20function.art)
> Adds FFI example to call function

- src/helpers/arrays.nim
- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
Fix the behavior according to #876
Fixes #876 
Running on my local build:
> [Collections/remove] fixing `.once` behavior

- src/library/Paths.nim
It's not so important because `module` should be replaced on future. But, for while, why not fix it temporarily? 🙂 
Fixes #878
My local build:
> Add support of module function for windows

- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
Add literal support to slice functions.
Fixes #844
Running on my local build:
> [Collections/slice] make it work with literals

- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
Adds support for windows path style.
For windows, both `\\` and `/` will be processed.
Fixes #878
On my local build:
> [Collections/split] fix `.path` behavior (including bug on Windows)

- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
So, `split.by` is working well at the `master` version. So, I just updated the unit-test to cover it.
Also, I'll open a new issue about the `split.every`.
Fixes #871
> [Collections/split] `.by` not working properly with Literal values?

- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
Fix `every.split` to work with literal types.
Also, I found [another error](https://github.com/arturo-lang/arturo/issues/885#issuecomment-1358069385) when I was testing it. But this, I opened in a new Issue: #887 
Fixes #885
On my local build:
> [Collections/split] `.every` is not working properly with Literal values

- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
The current implementation on master is returning strings with same size of `every` attribute.
It's not wrong for strings at the start or middle of the block, and some cases also not wrong at the end.
BUT, for some strings divided by certain numbers, the last item will return with wrong size
So, I fixed it to return the right size.
**Example**
*Current implementation:*
```
; This code
split.every: 3 "Manchester"
; returns a block with:
; [Man che ste r]
; string of size 3, string of size 3, string of size 3 and string of size 3???
```
The real case of this problem is described on issue #887 
*The new implementation*
```
; This code
split.every: 3 "Manchester"
; returns a block with:
; ; [Man che ste r]
; stringsof size 3, string of size 3, string of size 3 and string of size 1
```
The …
> [Collections/split] `.every` is not working properly with String values

- src/helpers/csv.nim
- src/library/Files.nim
- tests/unittests/lib.files.art
- tests/unittests/lib.files.res
> [Files/read] add support for different delimiters when in `.csv` mode

- src/helpers/arrays.nim
- src/helpers/dictionaries.nim
- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
`contains?.deep` and `in?.deep` should search recursively for some value in a container (`:block` or `:dictionary`) and return a `:logic`.
Fixes #958 #955
> [Collections] add `.deep` attribute for `contains?` & `in?`

- src/library/System.nim
- src/vm/env.nim
- tests/unittests/lib.system.art
- tests/unittests/lib.system.res
> or, perhaps even better, make our existing cpu field a dictionary with two fields:
I followed this approach, making `cpu` a `:dictionary` with two fields: `type` and `endian`.
Fixes #1036
--- 
`cpu` is now a dictionary with two literals: `arch` (the old `type`) and `endian`.
> [System/sys] add info about endianess

- .github/workflows/freebsd.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/netbsd.yml
- .github/workflows/openbsd.yml
- .github/workflows/release.yml
- .github/workflows/windows.yml
- build.nims
- docs/website/theme/index.html
- src/vm/env.nim
What this PR does:
- Roughly speaking, whenever we had `x86_64` for 64-bit builds, we'll now have `amd64` (same for `sys\cpu\arch` and the binary names)
- If running on a 32-bit system, instead of Nim's Linux-ish `i386`, `sys\cpu\arch` will show `x86` (same as our binary releases)
- Add OpenBSD & NetBSD to the list of supported OS'es (in terms of builds & releases)
Fixes #1035
> Sanitize arch names in binaries & releases + workflows cleanup

- src/library/Converters.nim
This update explains why you **must** use `@` for negative fields when converting to `:rational`s and `:complex`es, and add missing example for `:rational` type. 🙂 
Related to #1075
> [Converters\to] update usage examples for `:complex` and `:rational`

- src/library/Core.nim
- src/vm/errors.nim
- tests/errors/assertion.ensureWithCustomMessage.art
- tests/errors/assertion.ensureWithCustomMessage.res
Adds an attribute to print a custom message when `ensure` fails.
Fixes #1061
> [Core/ensure] add option for custom message

- src/vm/values/value.nim
On my local build:
Fixes #1074, related to #1072
> [Arithmetic\add & sub] doesn't work for `:color` literals

- src/vm/values/printable.nim
`as.code` wasn't returning valid code for `:rational` and `:complex` types when one of these fields were a negative number.
What I did, was support these cases.
Before:
```red
a: to :rational [3 5]
print as.code a - 1
; => to :rational [-2 5]
b: to :complex [1 2]
as.code b - 2
; => to :complex [-1.0 2.0]
```
Now:
```red
a: to :rational [3 5]
print as.code a - 1
; => to :rational @[neg 2 5]
b: to :complex [1 2]
as.code b - 2
; => to :complex @[neg 1.0 2.0]
```
As we may know, `to rational [-2 5]` is invalid, since `-` is the same as `sub`, and it doesn't turn `2` into a negative number.
So, I decided to turn these numbers into positive, add a `neg` function to it and add a `@` that is needed here.
Related to #1075
> [Converters\as] update formatting to support negative fields for `:rational` and `:complex` types

- src/helpers/ranges.nim
- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
There is two problems here, the main problem is described in the issue #1097, and the other is described [in my comment](https://github.com/arturo-lang/arturo/issues/1097#issuecomment-1480090093).
1. `last` was internally trying to generate an infinite block to get the last element. Obviously it crashes, since we don't have infinite memory and it would iterate infinitely until **never** reaches the infinite number... (fixed on [9dd1577](https://github.com/arturo-lang/arturo/pull/1100/commits/9dd15775f69b8fc2d3e16a73cd3279a1108f3657))
2. even solving the 1st problem, it still generates a block (`O(n/step)` amortized) to get the last number, but **we just want the last number**.
Fixes #1097
- returns a `:range` instead of `:block` for `last.n`
> [Collections\last] improve function's performance for range types

- src/library/Converters.nim
- tests/unittests/lib.converters.art
This PR properly closes (the already closed) #1075. Basically, try to convert an improper `:block` causes an undefined behavior, what is the worst case as possible to a production code.
- Fixes #1075
> [Converters\to] fix behavior when converting erroneous Block -> Complex/Rational

- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
> It should have the same behavior as for non-literals.
>
> ```red
> $> a: ["Arturo" " Nim" " Ruby" " Python", " C", " CoffeeScript"]
> $> split.at: 4 'a
> $> a
> ; => [[Arturo  Nim  Ruby  Python  C] [ C  CoffeeScript]]
> $> b: ["Arturo" " Nim" " Ruby" " Python", " C", " CoffeeScript"]
> $> split.at: 4 b
> ; => [[Arturo  Nim  Ruby  Python] [ C  CoffeeScript]]
> ```
- Fixes #1118
- Related to #669
> [Collections\split] fix `split.at` for literal values

- src/library/Converters.nim
- src/vm/errors.nim
- tests/errors/runtime.RangeWIthZeroStep.art
- tests/errors/runtime.RangeWIthZeroStep.res
It throws an error when `.step` attribute be assigned as 0.
Fixes #1041
> [Converters\range] `.step` can't be 0

- tests/unittests/lib.comparison.art
- tests/unittests/lib.comparison.res
Unit-test for [Comparison Lib](https://arturo-lang.io/documentation/library/comparison/).
This'll be a veeeery long list...
> Add unit-test for Comparison Library

- src/library/Converters.nim
Just add missing documentation examples to `range`...
Fixes #1170
> [Converters\range] add documentation example

- src/vm/values/comparison.nim
- tests/unittests/lib.comparison.art
- tests/unittests/lib.comparison.res
`:complex` types for now can be compared if they are _equal_, but the same is not real for _less_ or _greater_ comparisons,
So I'm adding this support.
Fixes #1150
> Add better comparison support for `:complex`

- src/library/Numbers.nim
- src/vm/values/value.nim
- tests/unittests/lib.numbers.art
- tests/unittests/lib.numbers.res
At the moment, `ceil`, `floor` and `round` just work with `:integer`s and `:floating`s, so I'm adding support to `:rational` values...
```red
ceil to :rational @[7 2] 
; => 4
ceil to :rational @[neg 7 2] 
; => -3
floor to :rational @[7 2]     
; => 3
floor to :rational @[neg 7 2] 
; => -4
round to :rational @[21 10]
; => 2
round to :rational @[neg 7 2]
; => -4
```
> Just a minor detail, I added some more unit-tests to `Numbers\clamp` too. :)
[Suggested by Krenium on Discord][discord-message]
[discord-message]: https://discord.com/channels/765519132186640445/829324913097048065/1105639192626745474
> [`Numbers\{ceil,floor,round}`]: add support to `:rational` values

- src/library/Numbers.nim
- tests/unittests/lib.numbers.art
- tests/unittests/lib.numbers.res
Enhance `clamp` adding support to more types
> clamp is actually based on Value comparisons and since Value comparisons are already in place (in the PR) for Rational values, this should just require updating the function signature (add support for Rational, apart from Integers and Floating-point numbers).
> 
> P.S. I'm not sure it'll work extremely well right now, but once the PR is merged, it will. But we could definitely do this^ part now... (@ name: « Takemichi if you have time, you can certainly go on 😉 ; if not, I'll do it myself! 🙂 )
[this message from @drkameleon][discord]
[discord]: https://discord.com/channels/765519132186640445/829324913097048065/1105770438111539200
> [Numbers\clamp]: add support for more types

- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
Fixes #1190
`drop` and `take` has some issues to be deal that returns `SIGSEVG`.
I'll care about their parameters as `collection`, the first one, and `number`, the second one.
How I handled these issues:
- ```red
; `take` implements this well, look:
take [1 2 3] 4 ; => [1 2 3]
drop [1 2 3] 4 ; => []
```
- ```red
drop [1 2 3] neg 1 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
; how should we handle this?
```
- ```red
; `take` implements this well for other `collection`'s kind, look:
take [1 2 3] 4 ; => [1 2 3]
take 1..3 4 ; => [1 2 3]
```
- ```red
; `take` implements this well for other `collection`'s kind, look:
take [1 2 3] 0 ; => []
take 1..3 0 ; => []
```
- ```red
take [1 2 3] neg 1 ; timeout: sending signal KILL to command …
```
> [Collections\drop & take] fix SIGSEGV errors

- examples/rosetta/tau number.art
- src/library/Numbers.nim
Just add the `tau` constant, as it was for `pi`.
* Fixes #1031
> [Numbers\tau] create constant

- src/library/Comparison.nim
- tests/unittests/lib.comparison.art
- tests/unittests/lib.comparison.res
Adds support to order insensitive range limits.
Basically, `between?` has 3 arguments: `value`, `rangeFrom` and `rangeTo`. 
So why `rangeFrom` can't be greater than `rangeTo`? So, I'm implementing this.
* Fixes #1146
> [Comparison\between?] add support for order insensitive limits

- src/library/Numbers.nim
I did minimal changes on it, just adding `Rational` type to argument list into functions that I think that should support them, and adding it to return list too for functions that already returns a `:rational` but it's not annotated.
Also, I did not need to change anything more, since these functions are using `asFloat` internally, and returning a `:floating` at the end.
* Fixes #1185
> [Numbers] add rational supports to its functions

- src/library/Comparison.nim
- tests/unittests/lib.comparison.art
- tests/unittests/lib.comparison.res
Fix `between?` behavior. It was returning true for some values unsupported by `<`/`>` comparisons.
I worked very well then for number-kind values, but for other types, does not.
I discovered that when I was doing the PR #1209.
The new algorithm takes more steps, but it will work well for every cases.
- Fixes #1213
> [Comparisons\between?] fix behavior

- src/helpers/webviews.nim
- src/vm/errors.nim
Add a proper error throw, instead of print it on the terminal.
Summary:
- Creates `RuntimeError_CompatibleBrowserNotFound`: when the compatible browser is not found, it raises an error
- Creates `RuntimeError_CompatibleBrowserCouldNotOpenWindow`: when the compatible browser can't open a window, it raises an error
- Replaces all `echo "some error message"` by these respective runtime errors.
----
- Fixes #1222
> [helpers\webview] Properly raise error for browser related things

- src/library/internal/Net/serve.art
Apparently, `match` options have been changed and we must update the internal implementation so that everything keeps working like before.
Probably provides a fix for #1239 ?
> Net/serve: minor fix

- src/helpers/charsets.nim
Add Vietnamese support, based on: [_Vietnamese language_ by Wikipedia, 2023][wiki-vi] and [_How to Learn the Vietnamese Alphabet: An In-Depth Guide_ by Julian, 2021][f3m]
- Fixes #558
[wiki-vi]: https://en.wikipedia.org/wiki/Vietnamese_language
[f3m]: https://www.fluentin3months.com/vietnamese-alphabet/
> [Helpers\charset] add Vietnamese alphabet support

- src/helpers/helper.nim
- tests/unittests/quantities.art
This PR cleans `helper.nim` up and refactor some functions, making them more readable and maintainable.
- Related to #596
> [Helpers\helper] Refactor helper.nim

- bench
- bench-log
- src/vm/values/comparison.nim
Benchmarks and tries to replace the ugly `case`/`of` by our newer, faster? and more readable approach `getValuePair`.
- Fixes #1149
> [VM\value\comparison]: Clear comparisons with `getValuePair`

- src/library/Core.nim
A short demonstration:
- Fixes #1325
> [Core\var]: add support for `:word`

- src/library/System.nim
- src/vm/vm.nim
Adds support for local config and adds proper documentation.
Basically, it checks first for `config.art` on the current directory, 
if there is nothing it picks up the global one from `~/.arturo/stores/config.art`.
- Fixes #1216
> [System\config] Add support for local config

- src/vm/ast.nim
- src/vm/eval.nim
- src/vm/exec.nim
Right now, this:
```ruby
define :person [
init: constructor [
name :string
surname :string
]
check: method [][
inspect this
]
]
define :personWrapper [
init: method [n, s][
\pers: to :person @[n, s]
]
doSth: method [][
\pers\check
]
]
a: to :personWrapper ["John" "Doe"]!
a\doSth
b: to :personWrapper ["Jane" "Doe"]!
b\doSth
```
leads to this:
```
[ :person
name     :        John :string
surname  :        Doe :string
]
[ :person
name     :        John :string
surname  :        Doe :string
]
```
The cause is that `this\pers` inside `doSth` has already been embedded the first time the function was evaluated. And since - for performance reasons - we tend to store evaluated blocks (apparently, a bit too much), the next time this function is called, with a different object, the same one is …
> Fix AST handling of method calls

- src/library/Core.nim
Only changed one line in builtin 'var' example string, it should show 2 instead of a when `print var 'a` is performed. No other changes has been made
> Fix minor error in 'var' example

- config.nims
- src/extras/linenoise.nim
- src/extras/md4c.nim
- src/helpers/markdown.nim
- src/helpers/repl.nim
ref https://forum.nim-lang.org/t/11612
> fixes `LinenoiseCompletions` types incompatible with gcc 14

- src/library/Reflection.nim
Shows that `attr?` does not pop the attributes' stack.
Related: https://discord.com/channels/765519132186640445/1245435661495046144
Thanks to @BNAndras.
> [Reflection\attr?] update the docs to cover behavior

- docs/website/pages/documentation/language.art
The language documentation has this section:
>💡 For the complete of recognized symbols in Arturo, you may have a look at here.
However, looking at the highlighted code, I don't really see the symbols.
Fixes https://github.com/arturo-lang/arturo-lang.io/issues/7
> docs: update symbols link

- src/vm/values/custom/vcolor.nim
This PR contains additions, cleanup, and corrections to the source file in subject regarding the following statement.
> Arturo lacks Aqua and Fuchsia and has incorrect values for LightSteelBlue, DarkSlateGray, and DarkGray
> [values/custom/vcolor] add missing colors & minor fixes

- src/helpers/combinatorics.nim
- src/library/Collections.nim
- tests/unitt/lib/collections/combine.test.art
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
Collections: allow bigger sizes for `combine` and `permutate` with `.repeated` option.
https://discord.com/channels/765519132186640445/1283495508354011219
closes https://github.com/arturo-lang/arturo/issues/1605
>  Collections: Fix .by: in permutate and combine for values <= 0 and bigger than length.

- src/vm/packager.nim
Currently, executable packages don't have aliases that function properly in Windows. This should solve that.
> Add Windows support for executable package aliases

- src/vm/packager.nim
Fix for previous PR. This should now correctly call arturo and also suppress the command output for that.
> Add support for executable package aliases in Windows (fixed)

- src/vm/packager.nim
This change deletes executable package aliases when uninstalling packages in Windows.
> Remove executable package alias when uninstalling in Windows

- src/library/Collections.nim
Fixes the behavior of magic method `in?`
```
define :set [
init: constructor [predicate]
contains?: method [item][
call \predicate @[item]
]
]
iseven: function 'x [(x % 2) = 0]
even: to :set ['iseven]!
print contains? even 2
print in? 2 even
print 2 ∈ even
```
used to output `true false false`. Now it outputs `true true true`.
> Fix in? magic method

- src/scripts/console.art
Add `Repl\verbose?` to control printing the last value of the stack in the repl.
> Add Repl\verbose? + update syntax in console.art

- docs/website/pages/documentation/command line.art
- docs/website/pages/documentation/in a nutshell.art
- docs/website/pages/documentation/language.art
- src/library/Core.nim
> Various documentation additions

- examples/rosetta/create a file on magnetic tape.art
- examples/rosetta/create a file.art
- examples/rosetta/file input-output.art
- examples/rosetta/fractal tree.art
- examples/rosetta/goldbach's comet.art
- examples/rosetta/hello world - line printer.art
- examples/rosetta/json.art
- examples/rosetta/make directory path.art
- examples/rosetta/remove lines from a file.art
- examples/rosetta/take notes on the command line.art
- examples/rosetta/write entire file.art
- src/library/Files.nim
- tests/unittests/lib.files.art
- tools/genaiguide.art
- tools/gendep.art
- tools/rc.art
- tools/sitegen.art
Swap write arguments.
Advantages:
1. pipes
2. alias
> Swap write arguments

- src/library/Sockets.nim
Basically, the only thing Arturo currently supports (and quite well, actually) is *blocking* connections, hence all of the examples so far were with `listen.blocking`.
Instead of doing it like this, this PR:
- completely removes the `.blocking` option
- internally sets it as the default mode
And if in the future we actually add support for *non-blocking* sockets, we could add an `.async` option for that...
> [Sockets\listen] remove `.blocking` option

- tests/unitt/lib/collections/couple.test.art
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
Migrates tests to `unitt`. Since #1786 added the feature of accept literals, as it is for `decouple`, I think this should be better to be solved in another PR. :wink:
- Ref.: #1786
> [Collections\couple] Migrate tests to `unitt`

- src/library/Logic.nim
Typo reported by SamwiseTheBrave at https://discord.com/channels/765519132186640445/829324913097048065/1330200600599728218.
> Fix typo in `or?` example

- src/library/Collections.nim
- src/library/Core.nim
These two function descriptions contain text between angle brackets. It seems this gets formatted as HTML and then not properly rendered. 
The corresponding HTML is ```<h3 class="subtitle is-4 is-spaced">pop top<number>values from stack</number></h3>```.
I changed number to N since that reads a little clearer to me.
> Remove formatting issues in docs related to  HTML tags

- .github/workflows/ci.yml
- config.nims
- src/extras/webview.nim
- src/extras/window.nim
See also: https://discord.com/channels/765519132186640445/1302349362411737168/1302349362411737168
> Fix webkit dependencies on Ubuntu 24+

- src/library/Collections.nim
- tests/unittests/lib.collections.art
- tests/unittests/lib.collections.res
> [Collections/split] implement split.by support for `:char`

- src/helpers/strings.nim
- src/library/Strings.nim
> [Strings] Add Char support for `whitespace?` + minor fixes

- src/library/Core.nim
- src/scripts/console.art
Updates Documentation (with the example of the `discard` function) and deprecates the attribute. Also updates depending parts of the deprecated one, like the `console.art`.
Fixes #1870
> [Core\unstack] Deprecate `unstack.discard`

- tools/unitt-tester.art
> un-update unitt to 1.1.2 again

- tools/sitegen.art
The problem is namely with `as.code` (that has been replaced by `express`)
The change affects however the `sitegen.art` script (and thus the automatic documentation generation).
Possible similar issue: https://discord.com/channels/765519132186640445/829324913097048065/1360458011222609980
> Fix internal references to deprecated stdlib functions

- src/helpers/conversion.nim
It could also handle: 
- `:pathLabel`
- `:pathLiteral`
since they are quite similar.
> [!NOTE]
> The PR isn't anything high-priority or urgent, just me using it as an "easy-entry" excuse to get back to working on 🦂... hehe)
Fixes #1640
> Add support for `:path` to `:block` conversions
