arturo-lang/arturo

.github/workflows/linux.yml
.github/workflows/windows.yml

Skip CI when only files of `paths-ignore` were changed.
see: [push/pull_request.paths-ignore - GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths).

chore: add condition to run CI

---

src/system/update.art

changed to new ./install script in updater

---

.github/workflows/check.yml

WIP: Added Code Linter workflow

---

.github/labeler.yml
.github/workflows/labeler.yml

Added PR Labeler action

---

src/vm/eval.nim

Fixed an issue with `->` (not working after code cleanup).

Debug and fix arrowright

---

src/library/Collections.nim
src/library/Core.nim
src/library/Crypto.nim
src/library/Databases.nim
src/library/Iterators.nim
src/library/Reflection.nim
src/library/Strings.nim
src/library/System.nim

Add missing examples

---

README.md

Correct the lower case "t" in Smalltalk

---

src/vm/errors.nim
src/vm/exec.nim
src/vm/lib.nim

Checking for argument type errors when each (built-in) function is called is costly and messy. We'll have to clean this up. :)

Sanitize required parameters handling

---

.github/workflows/freebsd.yml
.github/workflows/release.yml

See: https://forum.nim-lang.org/t/9510

Fix FreeBSD workflow and set Nim to 1.6.6

---

src/helpers/arrays.nim
src/library/Collections.nim
src/vm/values/clean.nim

- This functions must to modify `InPlaced.a`
- This must to don't return a new block, just do the above
> *"In a few words: in-place modification"* - @drkameleon 
from [Discord](https://discord.com/channels/765519132186640445/829324913097048065/1030392749339451442)
Fixes #756

add proc `cleanAppendInPlace`

---

src/library/Core.nim

I added an example of how to use relative importing in arturo using 'do function.
I also added a short explanation of what are the differences between just import a variable and function.

Adds relative module importing example

---

tests/unittests/lib.collections.art
tests/unittests/lib.collections.res

This PR adds some unit tests for cover Arturo's Collection Library.
> Note: It is not complete yet. 
And I added some notes too for problems that I found and some suggestions.

Creates Unit Tests for Collections module

---

src/library/Collections.nim
tests/unittests/lib.collections.art
tests/unittests/lib.collections.res

Add literal support to extend functions.
Fixes #843
Running on my local build:

[Collections/extend] make it work with literals

---

.github/workflows/check.yml
.github/workflows/freebsd.yml
.github/workflows/labeler.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/netbsd.yml
.github/workflows/openbsd.yml
.github/workflows/release.yml
.github/workflows/web.yml
.github/workflows/windows.yml
src/extras/libclipboard.nim
src/extras/webview.nim
src/extras/window.nim
version/changelog.md

Add workflows for NetBSD and OpenBSD + Misc. cleanup

---

src/vm/values/comparison.nim
tests/unittests/lib.comparison.art
tests/unittests/lib.comparison.res

[VM/values/comparison] add `>` & `<` support for Date values

---

tests/unittests/lib.arithmetic.art
tests/unittests/lib.arithmetic.res

Since @drkameleon asked me to revise the unit-test and check if everything is ok here, I'm doing this PR.
He did an awesome work in #1077 and #1104 that fixed the most of the bugs and strange behaviors we had sometime ago found in #1072.
- Related (chronologic order)
- #1072
- #1077
- #1104

[Tests\Arithmetic] revising unit-tests

---

src/helpers/bignums.nim

Related to #1004 (For now, we're to just handle the GMP side of the equation; if everything goes well, the rest will follow!)

Add bignum support for rationals

---

src/extras/linenoise.nim
src/helpers/repl.nim

Fix compilation on arm64 macOS

---

src/library/Collections.nim
src/library/Converters.nim
src/library/Core.nim
src/library/Numbers.nim

Add some missing usage examples to documentation.
- Fixes #1187
- Removes #1170's TODO

Fill documentation usage

---

src/scripts/update.art

Rewrites updater that is broken as said in #1181.
- Fixes #1181
[breaking-changes-comment]: https://github.com/arturo-lang/arturo/pull/1182#issuecomment-1538706614

[scripts\update.art] - rewrite

---

src/library/Core.nim

* Add a note to avoid confusion between different compilers or OSes
* Fixes #1194

[Core\call] update documentation usage

---

src/vm/values/comparison.nim
tests/unittests/lib.comparison.art
tests/unittests/lib.comparison.res

Add support for `:unit` values and update unit-tests.
- Fixes #1210

[Comparisons]: Add support for Unit values

---

src/library/Converters.nim
tests/errors/runtime.FileNotFound.1.art
tests/errors/runtime.FileNotFound.1.res

[Concerters\array] properly raise error when file not found

---

src/library/Collections.nim
tests/unittests/lib.collections.art
tests/unittests/lib.collections.res

This PR adds get's support to complex numbers, making its fields accessible using dictionary or array notation...

[Collections\get]: add complex numbers fields support

---

src/vm/values/operators.nim

[Vm\values\operators] replace `helpers/maths` by `std/math`

---

src/vm/values/value.nim

Thanks to https://adventofcode.com/2023/day/14. 🚀 
Fixes #1336

VM/values/value: properly copy nested Block values

---

.config/utils/cli.nims
.config/utils/ui.nims
build.nims

- **Bug fix**:
- `getPositionalArg` returns a clear message to the user
- **Breaking changes**:
- `build` is the default command, so `./build.nims` will trigger the `build` if none command have been provided
- **Enhancements**:
- The initial and ugly hints from the Nim's compiler were hidden
- `help` is triggered for wrong commands
- `cli.nims`'s internal variables were grouped into `CLI`
- set a `CLI.defaultCommand` variable to decouple code
- **Documentation**:
- Minor updates

build: Better user interface for the builder script

---

src/library/Collections.nim

[Collections\methods] add documentation

---

src/library/Types.nim

[Types\constructor] add documentation

---

src/library/Types.nim

[Types\method?] add documentation

---

src/library/Types.nim

[Types\defined?] add documentation

---

src/library/Types.nim

[Types\sortable] add documentation

---

src/library/Core.nim

[Core\method] add documentation

---

src/library/Types.nim

[Types\is] add documentation

---

src/library/Core.nim

[Core\let]: add support for `:word`

---

src/library/Collections.nim

[Collections\dictionary]: add documentation example for `.raw`

---

src/library/Collections.nim
tests/unittests/lib.collections.art

[Collections\first]: clip upper range when n > size of the collection

---

src/library/System.nim

[System\script]: add documentation

---

src/library/Collections.nim
src/library/Converters.nim
src/library/Core.nim
src/vm/checks.nim

Just cleaning some TODOS from closed and solved issues that did not erased them from the code.
I just checked each of them, since the `github-actions` bot closed a lot of issues recently without being fixed tho.

Clear some TODOS

---

src/library/Iterators.nim

Makes sure that parameters block is either literals or words
- Fixes #1137

[Iterators]: check block value for  `fetchParamsBlock`

---

src/vm/parse.nim

In connection with: https://github.com/arturo-lang/arturo/pull/1556

VM/parse: fix parsing for "incomplete" floating-point numbers

---

src/library/Bitwise.nim
src/library/Collections.nim
src/library/Crypto.nim
src/library/Dates.nim
tests/unittests/lib.collections.art
tests/unittests/lib.collections.res
tests/unittests/lib.crypto.art
tests/unittests/lib.crypto.res
tests/unittests/lib.dates.art
tests/unittests/lib.dates.res

Basically, we have a looot of issues opened just to implement this.
So, let's go!
You can see all pending issues here: [Issues (:pathLiteral)][path-literal-issues]
- Fixes 
- Fix #1502 
- Fix #1501
- Fix #1500 
- Fix #1499 
- Fix #1498 
- Fix #1497 
- Fix #1496 
- Fix #1495
- Fix #1494
- Fix #1493
- Fix #1492
- Fix #1491
- Fix #1490 
- Fix #1489
- Fix #1488 
- Fix #1487
- Fix #1486
- Fix #1485 
- Fix #1484
- Fix #1483 
- Fix #1482 
- Fix #1481
- Fix #1480
- Fix #1471 
- Fix #1470
- Fix #1469
- Fix #1468 
- Fix #1467 
- Fix #1466 
- Fix #1465 
- Fix #1464 
- Fix #1463
- Fix #1462 
- Fix #1461 
- Fix #1460
- Fix #1459
- Fix #1458 
- Fix #1457 
- Fix #1456 
- Fix #1455 
- Fix #1454
- Fix #1453 
- Fix #1452 
- Fix #1451 
- Fix #1450
---
> [!NOTE]
> Tests added are property-based, and they …

Add `:pathLiteral` support to Libraries

---

src/library/Core.nim

Core\call: add support for Method values

---

src/vm/values/custom/vquantity.nim

fix currency-api link

---

.config/who.nims

We need to check why this is breaking things
---
Related: https://discord.com/channels/765519132186640445/829324913097048065/1213150384353189980

[builder]: fix release mode

---

src/vm/env.nim

System\sys: add information about CPU cores

---

src/helpers/packager.nim

Fix argument passing for package executables

---

src/vm/errors.nim

Related: https://discord.com/channels/765519132186640445/829324913097048065/1242060547420065874

[error] fix underline formatation for windows terminal

---

config.nims

**See also:** https://discord.com/channels/765519132186640445/829324913097048065/1243055988349865994

Debug `pkg-config`-related issues on Windows builds

---

.github/FUNDING.yml
README.md

Update donations info & add sponsors list

---

examples/rosetta/10001th prime.art

Improve 10001th prime example

---

src/library/Numbers.nim

Add functionality to convert a block of digits [1 2 3] to a number 123.

library/Numbers: Convert digits to number

---

examples/rosetta/almost prime.art
examples/rosetta/find words with alternating vowels and consonants.art

Improve example find words with alternating vowels and consonants

Improve roseta examples

---

.github/labeler.yml

Just some GitHub-related housekeeping...

Update automatic labels for library modules

---

src/library/Collections.nim

Add alias ∈ for in?

---

.github/workflows/ci.yml

Restore artifacts in normal CI builds

---

src/library/Io.nim

input ø to read a single char

---

src/library/Sets.nim

Change superset alias to ⊇

---

docs/website/pages/documentation/in a nutshell.art

Fix custom types example.
I'm not sure about the comparator, since deleting that line doesn't change anything.

Fix custom types example

---

src/scripts/console.art

Unify options in console.art

---

src/library/Ui.nim

**See also:** https://discord.com/channels/765519132186640445/829324913097048065/1301857407659671552

[UI\webview] fix documentation example

---

src/library/Collections.nim

**See also:** https://discord.com/channels/765519132186640445/829324913097048065/1315029393957060678

Raname `.safe` to `.field`

---

src/library/Core.nim

I have slightly changed the examples for `alias` and `alias.infix` so they work with modern Arturo. Just a couple of `!`s and accounting for the fact that `-->` is now a builtin.

Update alias example for modern Arturo

---

src/library/Core.nim

[Core\when] Fix minor typo in documentation example

---

docs/website/pages/documentation/library/files/_index.art

See also: https://discord.com/channels/765519132186640445/829324913097048065/1324991935688998963

Remove duplicate example from Files module doc page

---

tests/unitt/lib/collections/array.test.art

This PR add some unit-tests using `unitt`. 
I'm not adding all the unit-tests, since `array` has a bug that needs to be fixed in other PR.
The but I mentioned was already fixed in #1786, but since `array` is one of the most used functions, I prefer to include this in a separated PR.
- From: #1786

[Collections\array] add `unitt` tests

---

.github/workflows/ci.yml

Minot edit: Remove debugging output step

---

.github/workflows/build-update.yml

Sanitize build numbers (Iteration 1)

---

.github/workflows/docgen.yml
docs/website/theme/components/navbar.html

Add branch info to website navbar

---

tools/miniwebize/webize.art

Fix module documentation pages

---

.github/workflows/docgen.yml

Fix module documentation pages (Iteration 2)

---

docs/website/tools/updatecopyrights.sh

There are valid arguments to leave it as-is and only updated once a new version is published.
But the truth is I myself think would conclude that the project is abandoned or sth - while it's anything *but*.
So, let's fix that! 🚀 
**See also:** https://discord.com/channels/765519132186640445/831551807418794014/1317866979000061982

Change copyright year of current documentation

---

examples/rosetta/abc incremental counts.art
examples/rosetta/abc incremental counts.res

Thanks to @chunes3 😉 🚀 
See also: https://discord.com/channels/765519132186640445/829324913097048065/1353008112822517800
Rosetta Code: https://rosettacode.org/wiki/ABC_incremental_counts#Arturo

Add RC example for "ABC incremental counts"

---

examples/rosetta/dice game probabilities.art

Thanks @chunes3 ! 🚀 
**See also:** https://rosettacode.org/wiki/Dice_game_probabilities#%7B%7Bheader%7CArturo%7D%7D

Added "Dice game probabilities" RC solution

---

docs/website/pages/documentation/library/converters/_index.art

Post-merge cleanup
**See also:** #1902

Remove Converters from the documentation

---

examples/rosetta/munching squares.art

Thanks @chunes3 !
**See also:** https://rosettacode.org/wiki/Munching_squares#Arturo

Added "Munching squares" RC solution

---

src/helpers/intrinsics.nim

**See also:** https://github.com/arturo-lang/arturo/issues/1941 & https://discord.com/channels/765519132186640445/829324913097048065/1362683653762846840

[Helpers\intrinsics] Distinguish between `long` & `long long` based on current plaform

---

src/vm/parse.nim

Fix #1875 symbol literal not parsed correctly

---

.github/workflows/docgen.yml

See also: https://llmstxt.org/

Make our "AI tutorial" abide by `llms.txt`

---

src/library/Iterators.nim
tests/unitt2/lib/iterators/fold.test.art
tools/unitt2-tester.art

Fix #1873: fold.seed should return the seed for empty lists

---

.github/workflows/update.yml

Fix Update workflow

---

.github/workflows/update.yml

[Website] Fix binary paths @ master 
